# ==============================================
# Microservice Minimal Runtime
# ==============================================
FROM eclipse-temurin:25-jre-alpine

# Create a non-privileged system user for security
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app

# Copy the pre-built JAR generated by Jenkins in the 'Package Application' stage
# Note: Matching the 1.0.0-SNAPSHOT pattern from your target folder
COPY target/employee-service-1.0.0-SNAPSHOT.jar app.jar

# Run the container under safe non-privileged user access model
USER appuser

# Configure and expose application microservices port
EXPOSE 8080
ENV PORT=8080

# Configure JVM flags optimized for virtual-threads & containers
ENTRYPOINT ["java", "-XX:+UseG1GC", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]